### ISSUE TITLE
mutt colors look strange (compiled against slang)

### ISSUE THREAD

**Issue by toogy** [seletskiy/dotfiles#12]
Colors in mutt with theme_dark look strange.
Is this supposed to look like this?

<img width="746" alt="screen shot 2015-10-09 at 1 11 04 am" src="https://cloud.githubusercontent.com/assets/694873/10388898/a9a0609c-6e22-11e5-8a1a-abbf90f25209.png">

**Comment by seletskiy** [comment]
@toogy: unfortunately, I didn't patched dark theme after migrating from solarized to seoul256 color theme, so it's now broken.

If you will manage to look it fine, please, let me know, I'll glad to use it.

**Comment by kovetskiy** [comment]
@seletskiy @toogy I've patched Stanislav's mutt dark theme.
https://github.com/kovetskiy/dotfiles/blob/master/.mutt/theme_dark
![screenshot](https://cloud.githubusercontent.com/assets/8445924/10390953/4ca4c6d2-6e6b-11e5-9cf4-2ca7d792e379.png)

**Comment by toogy** [comment]
@kovetskiy thanks but it looks even worse for me :/

<img width="696" alt="screen shot 2015-10-09 at 11 57 37 am" src="https://cloud.githubusercontent.com/assets/694873/10402915/010db672-6e7d-11e5-9b9f-2407c664393a.png">

Shouldn't the dark gray messages (new messages) be blue? What's happening here? Why is it so complicated to get good mutt colors? :(

**Comment by kovetskiy** [comment]
@toogy blue color for new msg - LGFM
