### ISSUE TITLE
What/where is your custom Monaco font?

### ISSUE THREAD

**Issue by raehik** [seletskiy/dotfiles#13]
In your beautiful GIF in the readme for https://github.com/seletskiy/ash you use a font I can only assume to be Monaco (checking your dotfiles), but the 'a' glyph is different (IMO looks better). Did you make changes to it? Any info on where that glyph came from? Just curious and can't find the answer for the life of it.

**Comment by kovetskiy** [comment]
@raehik https://github.com/seletskiy/monaco-font

**Comment by seletskiy** [comment]
@kovetskiy: :+1:

**Comment by raehik** [comment]
Haha, thanks, didn't see that.
