### ISSUE TITLE
Mention DOTFILE_PROFILE propagation in readme

### ISSUE THREAD

**Issue by mechmind** [seletskiy/dotfiles#14]
For those who want to use just bootstrap and dotfiles scripts in their own configuration it will be useful to mention that DOTFILES_PROFILE should be remembered between runs.

**Comment by seletskiy** [comment]
@mechmind: Wow, are you using it?

**Comment by mechmind** [comment]
Yep, just started

**Comment by seletskiy** [comment]
@mechmind: Beware, soon it will be done via heaver & co!

**Comment by seletskiy** [comment]
@mechmind: thx!

**Comment by mechmind** [comment]
BTW how do you indent columns in profiles.txt? By hand? Or with some script?

**Comment by seletskiy** [comment]
@mechmind: Somethings like [`:Tabularize /\v +\zs!?\ze +/`](https://github.com/godlygeek/tabular) can be used to align columns. :godmode:

**Comment by mechmind** [comment]
Okay.
